from typing import Annotated, List, Literal, Optional, TypedDict

from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages


class _RequiredState(TypedDict):
    """Required fields — always present in the state."""

    messages: Annotated[List[BaseMessage], add_messages]
    iterations: int


class AgentState(_RequiredState, total=False):
    """
    State definition for the AuditGraph workflow.
    Acts as the contract between nodes.

    Required fields (always present): messages, iterations
    Optional fields (set by specific nodes): all others
    """

    guardrail_verdict: str
    plan: str  # Execution plan from Planner agent
    sql_query: Optional[str]  # SQL generated by Fiscal Agent
    code: Optional[str]  # Python code generated by Analyst Agent
    output: Optional[str]  # Final output returned to user
    error: Optional[str]  # Error from last execution attempt
    evaluation: Optional[str]  # Critic's feedback on generated code
    # Structured context fields (avoid injecting as HumanMessages)
    user_question: str  # Original user question extracted at guardrail
    table_list: List[str]  # Tables returned by list_tables_node
    schema_context: str  # Compact schema set by list_tables_node
    is_complex: bool  # True when query contains multi-step analytical keywords
    # Data gap detection (set by check_query_node + check_result_integrity)
    data_gap_detected: bool  # True when algorithmic check found a gap
    gap_reason: Optional[Literal["empty_result", "data_unavailable"]]
    gap_detail: Optional[str]  # Human-readable description of the gap
    gap_alternative: Optional[str]  # Suggested alternative table/approach
    gap_context: Optional[str]  # Pre-formatted context block injected into editor
    # Langfuse observability (set by workflow.run before graph.invoke)
    trace_id: str  # Langfuse trace ID (32-char hex) — links all node spans
    root_span_id: str  # Langfuse root span ID (16-char hex) — parent for node spans
