from typing import Annotated, List, Optional, TypedDict

from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages


class _RequiredState(TypedDict):
    """Required fields — always present in the state."""

    messages: Annotated[List[BaseMessage], add_messages]
    iterations: int


class AgentState(_RequiredState, total=False):
    """
    State definition for the AuditGraph workflow.
    Acts as the contract between nodes.

    Required fields (always present): messages, iterations
    Optional fields (set by specific nodes): all others
    """

    guardrail_verdict: str
    plan: str  # Execution plan from Planner agent
    sql_query: Optional[str]  # SQL generated by Fiscal Agent
    code: Optional[str]  # Python code generated by Analyst Agent
    output: Optional[str]  # Final output returned to user
    error: Optional[str]  # Error from last execution attempt
    evaluation: Optional[str]  # Critic's feedback on generated code
    # Structured context fields (avoid injecting as HumanMessages)
    user_question: str  # Original user question extracted at guardrail
    table_list: List[str]  # Tables returned by list_tables_node
    schema_context: str  # Schema DDL returned by get_schema_node
